---
title: "Other Distributions"
author: "John Rothen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(extraDistr)
```

## Introduction

This document is designed to provide an overview to the new distributions used in this project


### Beta Prime

This distribution isn't perfectly suited to survival curves, but when $0 <= a <= 1$, it is a monotonically decreasing distribution, with a slope that begins steeply negative and approaches 0 over time. 

PDF:  $f(x|\alpha\beta) = \frac{x^{\alpha-1}(1+x)^{-\alpha - \beta}}{B(\alpha,\beta)}$ where B is the Beta function and $\alpha, \beta$ > 0.

```{r beta prime}
# Density or ~ f(x)
dbetaP <- function(x, a, b){
  # a, b > 0 
  return(( x^(a-1) * (1+x)^(-1*a-b))/beta(a,b))
}

# CDF or ~ F(x)
pbetaP <- function(x, a, b){
  x2 <- x/(1+x)
  return(qbeta(x2,a,b))
}

# Survival or S(x)
sbetaP <- function(x, a, b){
  return(1-pbetaP(x,a,b))
}

# survival event density  or S'(x) = -f(x)

# hazard function or h(x)
hbetaP <- function(x, a, b){
  return(dbetaP(x,a,b) / sbetaP(x,a,b))
}

# cumulative hazard or H(x)
HbetaP <- function(x,a,b){
  return(-1*log(sbetaP(x,a,b)))
}



fs_betapr <- list(
  name = 'betapr',
  pars= c('shape1','shape2','scale'),
  location='scale',
  transforms= c(log,log,log),
  inv.transforms= c(exp,exp,exp),
  inits= function(t){c(mean(t),1/mean(t) + 1,1)}
)
flexsurv::flexsurvreg

idk <- seq(0,10,by=.01)
idk2 <- sapply(idk, function(x) dbetaP(x,a=1,b=.5))
idk3 <- sapply(idk, function(x) pbetaP(x,a=1,b=.5))
idk4 <- sapply(idk, function(x) sbetaP(x,a=1,b=.5))
idk5 <- sapply(idk, function(x) hbetaP(x,a=1,b=.5))
idk6 <- sapply(idk, function(x) HbetaP(x,a=1,b=.5))
 

plot(idk, idk2, main="PDF", type = 'l')
plot(idk, idk3, main="CDF", type = 'l')
plot(idk, idk4, main="Survival", type = 'l')
plot(idk, idk5, main="Hazard", type = 'l')
plot(idk, idk6, main="Cumul Haz", type = 'l')
```


### Birnbaum-Saunders

This distribution is an interesting modification of the normal distribution.


```{r}
dBirnSaun <- function(x, u, g, b){
  # u < x
  # g, b > 0
  chunk1 <- sqrt((x-u)/b)
  chunk2 <- sqrt(b/(x-u))
  return(
    ((chunk1 + chunk2)/ (2*g*(x-u))) * dnorm((chunk1-chunk2)/g)
  )
}

pBirnSaun <- function(x, u, g, b){
  q <-   ((sqrt((x-u)/b) - sqrt(b/(x-u)))/g)
  return(pnorm(q,0,1))
}

idk4 <- sapply(idk, function(x) dBirnSaun(x,u=-1,g=1,b=1))
idk5 <- sapply(idk, function(x) pBirnSaun(x,u=-1,g=1,b=1))
 
plot(idk, idk4)
plot(idk, idk5)

```


### Burr Type XII

AKA Singh-Maddala


```{r}
dBurrT12 <- function(x,c,k,l=1){
  return(
    c*k*(1/l)*((x/l)^(c-1)) * ((1 + (x/l)^c)^(-1*k - 1))
  )
}

pBurrT12 <- function(x,c,k,l=1){
  return(1-(1+(x/l)^c)^(-k))
}

idk6 <- sapply(idk, function(x) dBurrT12(x,c=1,k=1))
idk7 <- sapply(idk, function(x) pBurrT12(x,c=1,k=1))
 
plot(idk, idk6)
plot(idk, idk7)
```



### Cauchy

```{r}
dcauchy(1,1,1)
```