# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

derlang <- function(x, k, l, log = FALSE) {
    .Call(`_survshotgunR_derlang`, x, k, l, log)
}

perlang <- function(x, k, l, log = FALSE) {
    .Call(`_survshotgunR_perlang`, x, k, l, log)
}

dgamgomp <- function(x, b, s, beta, log = FALSE) {
    .Call(`_survshotgunR_dgamgomp`, x, b, s, beta, log)
}

pgamgomp <- function(x, b, s, beta, log = FALSE) {
    .Call(`_survshotgunR_pgamgomp`, x, b, s, beta, log)
}

dlogcauchy <- function(x, mu, sigma, log = FALSE) {
    .Call(`_survshotgunR_dlogcauchy`, x, mu, sigma, log)
}

plogcauchy <- function(x, mu, sigma, log = FALSE) {
    .Call(`_survshotgunR_plogcauchy`, x, mu, sigma, log)
}

dhypertab <- function(x, a, b, log = FALSE) {
    .Call(`_survshotgunR_dhypertab`, x, a, b, log)
}

phypertab <- function(x, a, b, log = FALSE) {
    .Call(`_survshotgunR_phypertab`, x, a, b, log)
}

dinvlind <- function(x, theta, log = FALSE) {
    .Call(`_survshotgunR_dinvlind`, x, theta, log)
}

pinvlind <- function(x, theta, log = FALSE) {
    .Call(`_survshotgunR_pinvlind`, x, theta, log)
}

